---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: hpanginx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: productcatalogue
  minReplicas: 1
  maxReplicas: 10
  metrics: 
  - type: Resource
    resource: 
     name: cpu
     target: 
        type: Utilization
        averageUtilization: 10
